# -*- coding: utf-8 -*-
"""Simple Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12pNwwcGLhEg7FRKGXZgrHUOGd2-xwyKC
"""

n1 = (input('Enter number 1: '))
n2 = (input('Enter number 2: '))
ans = 0
stop = 'exit'

print('This calculator can perform these functions - Addition(+), Subtraction (-), Division (/), Multiplication (*), Floor Division (//), Module/Remainder (%) and Exponent (**). Put the operator sign in the next input.')

print('To stop, write exit')

opn = input('What operation do you want to execute?: ')

def sum(n1, n2):
  return (int(n1) + int(n2))
def subtract(n1, n2):
  return (int(n1) - int(n2))
def divide(n1, n2):
  return float(int(n1) / int(n2))
def multiply(n1, n2):
  return (int(n1) * int(n2))
def floor_div(n1, n2):
  return (int(n1) // int(n2))
def modRem(n1, n2):
  return (int(n1) % int(n2))
def power(n1, n2):
  return (int(n1) ** int(n2))

def execute(opn):
  if (opn == '+'):
    print(sum(n1, n2))
  elif (opn == '-'):
    print(subtract(n1, n2))
  elif (opn == '/'):
    if (n1 == '0'):
      print('Division not possible.')
    else:
      print(divide(n1, n2))
  elif (opn == '*'):
    print(multiply(n1, n2))
  elif (opn == '//'):
    print(floor_div(n1, n2))
  elif (opn == '%'):
    print(modRem(n1, n2))
  elif (opn == '**'):
    print(power(n1, n2))

execute(opn)

n1 = (input('Enter number 1: '))
while n1 != 'exit':
  n2 = (input('Enter number 2: '))
  opn = input('What operation do you want to execute?: ')
  execute(opn)
  n1 = (input('Enter number 1: '))

print('You have exit the application.')

ask = input('Do you really want to exit this application? Write Y or N: ')

while ask != 'Y':
  n1 = (input('Enter number 1: '))
  while n1 != 'exit':
    n2 = (input('Enter number 2: '))
    opn = input('What operation do you want to execute?: ')
    execute(opn)
    n1 = (input('Enter number 1: '))
  ask = input('Do you really want to exit this application? Write Y or N: ')

print('The application is closed now.')